title: course3
description: course 3 sample
template:
  repo: course3-template
  name: course3
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
    # Step 2: Create a project board to view your work
  - title: Create a project board to view your work
    description: Create a project board to view your work # a description of the step, shown to the learner in the course progress page
    event: project.created
    actions: # a list of the actions that will occur when the step is triggered by an event
    - type: gate
      left: '%payload.project.name%'
      operator: ===
      right: "Project1"
      else:
        type: respond
        with: 01_try-again.md
    - type: respond
      with: 01_nice-work.md